# Generated by Django 4.1.2 on 2022-10-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descricao', models.TextField()),
                ('data entrada', models.DateField()),
                ('entrega', models.BooleanField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
