# Generated by Django 4.1.2 on 2022-10-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='entrega',
        ),
    ]
