# Generated by Django 4.1.2 on 2022-10-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_remove_tarefa_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='data entrada',
            new_name='dataEntrada',
        ),
    ]
